import type { Metadata, Viewport } from "next";
import Script from "next/script";
import "@/styles/globals.css";
import { satoshi } from "@/styles/fonts";
import TopBanner from "@/components/layout/Banner/TopBanner";
import TopNavbar from "@/components/layout/Navbar/TopNavbar";
import Footer from "@/components/layout/Footer";
import HolyLoader from "holy-loader";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Shopco",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
    <style dangerouslySetInnerHTML={{ __html: 'html.preta-pre-hide{visibility:hidden!important}' }} />
    <script dangerouslySetInnerHTML={{ __html:
      '(function(){try{var d=document.documentElement;d.classList.add("preta-pre-hide");' +
      'window.__pretaRevealPreHide=function(){d.classList.remove("preta-pre-hide")};' +
      'setTimeout(window.__pretaRevealPreHide,1500);}catch(e){}})();'
    }} />
  </head>
      <body className={satoshi.className}>
       
       <script
 async
  src="https://yash-loader-worker.pushkarnagwekar.workers.dev/?d=clothing-factory-zeta.vercel.app"
  data-api="https://app.pretasystems.com/api"
  data-debug="true">
</script>
        <HolyLoader color="#868686" />
        <TopBanner />
        <Providers>
          <TopNavbar />
          {children}
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
